# Generated by Django 5.2.1 on 2025-05-15 16:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('uploaded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_user', models.BooleanField(db_default=True)),
                ('timestamp', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultrabook_app.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('ai_model', models.CharField(max_length=100)),
                ('files', models.ManyToManyField(related_name='projects', to='ultrabook_app.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultrabook_app.project'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ultrabook_app.project'),
        ),
    ]
