# Generated by Django 5.2.1 on 2025-05-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrabook_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='desc',
        ),
    ]
