# Generated by Django 5.2.1 on 2025-05-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrabook_app', '0003_remove_project_files_alter_file_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.TextField(db_default='stars'),
        ),
    ]
