# Generated by Django 5.2.1 on 2025-05-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrabook_app', '0006_remove_message_conversation_message_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultrabook_app.project'),
        ),
    ]
