# Generated by Django 5.2.1 on 2025-05-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrabook_app', '0007_alter_message_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
