# Generated by Django 5.2.1 on 2025-05-30 13:56

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrabook_app', '0008_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='podcasts/')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultrabook_app.project')),
            ],
        ),
    ]
